export * from './avatar/AvatarPage'
export * from './chatbot/ChatbotPage'
export * from './home/HomePage'
export * from './information/InformationPage'
export * from './login/AuthCallbackPage'
export * from './login/LoginPage'
export * from './mypage/MypagePage'
export * from './not-found/NotFoundPage'
export * from './policies/MedicalNoticePage'
export * from './policies/PrivacyPolicyPage'
export * from './policies/TermsPage'
export * from './routine/RoutinePage'
export * from './settings/SettingsPage'
export * from './signup/SignupPage'
export { default as AttentionGamePage } from './training/AttentionGamePage'
export { default as JudgmentGamePage } from './training/JudgmentGamePage'
export * from './training/LanguageGamePage'
export * from './training/MemoryGamePage'
export * from './training/TrainingPage'
export * from './survey/SurveyPage';
